version: '3.8'

services:
  api:
    image: api-pda
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${API_PORT}:7173"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:${API_PORT}
      - ConnectionStrings__DefaultConnection=Server=${SQL_SERVER_HOST},${SQL_SERVER_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True

  client:
    image: client-pda
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - api
